version: '3.8'

services:
  psql:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - '5432:5432'
    volumes:
      - "./psql.sql:/docker-entrypoint-initdb.d/extensions.sql"
